version: '3.8'
services:
  fastify_backend:
    container_name: fastify_backend
    image: ismailsirma/fastify_backend:0.0.1
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on: 
      - postgres
    extra_hosts:
    - "host.docker.internal:host-gateway"

  postgres:
    container_name: postgres
    image: 'postgres:13'
    ports:
      - '5432:5432'
    restart: always
    env_file: .env
    volumes:
      - fastify_volume:/var/lib/postgresql/data
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge

volumes:
  fastify_volume: {}
